"title": "Extract Positions from rosbag data!",
"author": [
    { "name": "Kaan Ural"}
]

#### This notebook utilizes the bagpy python module to get and analyze the rosbags that are saved beforehand.
#### rosbags are collection of recorded data, in this case while manipulating the robot arm.

In [ ]:
import bagpy
from bagpy import bagreader
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Importing the data bag recorded from ROS

In [ ]:
b = bagreader('/home/kaan/AI/SevenDOF/Gazebo_ds/datasets/movement4_2024-04-13-15-45-58.bag')

[INFO]  Successfully created the data folder /home/kaan/AI/SevenDOF/Gazebo_ds/datasets/movement4_2024-04-13-15-45-58.

In [ ]:
b.topic_table

                Topics                   Types  Message Count  Frequency
0  /gazebo/link_states  gazebo_msgs/LinkStates         299994        NaN
1   /iiwa/joint_states  sensor_msgs/JointState          30001      100.0

In [ ]:
# Read the ROS topics
positions = b.message_by_topic('/gazebo/link_states')
angles = b.message_by_topic('/iiwa/joint_states')

# Put them into dataframes
df_poses = pd.read_csv(positions)
df_angles = pd.read_csv(angles)

In [ ]:
df_angles

,Time,header.seq,header.stamp.secs,header.stamp.nsecs,header.frame_id,name,position_0,position_1,position_2,position_3,...,velocity_4,velocity_5,velocity_6,effort_0,effort_1,effort_2,effort_3,effort_4,effort_5,effort_6
0,1054.683,105380,1054,681000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",0.000013,0.000071,-0.000026,-0.000045,...,0.000081,-0.000373,0.000070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1054.691,105381,1054,691000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",0.000013,0.000071,-0.000026,-0.000045,...,0.000081,-0.000373,0.000070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1054.701,105382,1054,701000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",0.000013,0.000071,-0.000026,-0.000045,...,0.000081,-0.000373,0.000070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1054.711,105383,1054,711000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",0.000013,0.000071,-0.000026,-0.000045,...,0.000081,-0.000373,0.000070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1054.721,105384,1054,721000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",0.000013,0.000071,-0.000026,-0.000045,...,0.000081,-0.000373,0.000070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29996,1354.639,135376,1354,641000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",2.351751,-0.147447,-1.175521,1.350805,...,0.006941,-0.007999,0.001160,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29997,1354.651,135377,1354,651000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",2.348598,-0.148008,-1.172338,1.348688,...,0.006939,-0.008152,0.001193,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29998,1354.661,135378,1354,661000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",2.345445,-0.148570,-1.169154,1.346571,...,0.006936,-0.008304,0.001226,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29999,1354.671,135379,1354,671000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",2.342291,-0.149132,-1.165970,1.344454,...,0.006934,-0.008455,0.001259,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30000,1354.681,135380,1354,681000000,NaN,"['iiwa_joint_1', 'iiwa_joint_2', 'iiwa_joint_3...",2.339138,-0.149693,-1.162786,1.342337,...,0.006931,-0.008606,0.001292,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_poses

,Time,name,pose,twist
0,1054.683,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
1,1054.683,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
2,1054.683,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
3,1054.683,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
4,1054.684,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
...,...,...,...,...
299989,1354.681,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
299990,1354.681,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
299991,1354.681,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
299992,1354.681,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...
299993,1354.681,"['ground_plane::link', 'iiwa::iiwa_link_0', 'i...",[position: \n x: 0.0\n y: 0.0\n z: 0.0\nori...,[linear: \n x: 0.0\n y: 0.0\n z: 0.0\nangul...

In [ ]:
# Delete name and twist(velocity) columns
df_poses_clean = df_poses.drop(['name','twist'], axis=1)

In [ ]:
poses = df_poses_clean.iloc[:,:]
poses

            Time                                               pose
0       1054.683  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
1       1054.683  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
2       1054.683  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
3       1054.683  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
4       1054.684  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
...          ...                                                ...
299989  1354.681  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
299990  1354.681  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
299991  1354.681  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
299992  1354.681  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
299993  1354.681  [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...

[299994 rows x 2 columns]

In [ ]:
# 3D position and orientation of every sample
poses.iloc[:3,1]

0    [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
1    [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
2    [position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\nori...
Name: pose, dtype: object

In [ ]:
# 3D position and orientation of every link in a sample
poses.iloc[:3,1][0]

'[position: \n  x: 0.0\n  y: 0.0\n  z: 0.0\norientation: \n  x: 0.0\n  y: 0.0\n  z: 0.0\n  w: 1.0, position: \n  x: 5.528009865141126e-08\n  y: -3.259223954579142e-08\n  z: 3.8642248596787443e-07\norientation: \n  x: 1.27621350506052e-08\n  y: -9.166620881576895e-07\n  z: -1.1954558673465723e-07\n  w: 0.9999999999995728, position: \n  x: 1.6411417776039058e-06\n  y: 2.7126937853644284e-07\n  z: 0.15000009398729025\norientation: \n  x: -2.6008785588195955e-07\n  y: -7.943889761683671e-07\n  z: 6.366197425863224e-06\n  w: 0.9999999999793864, position: \n  x: 1.7826460398504763e-06\n  y: 1.9706185802602994e-07\n  z: 0.3399999119053475\norientation: \n  x: 2.0373598748012738e-05\n  y: 0.7071081939477214\n  z: 0.707105367594735\n  w: -2.7488590820232617e-05, position: \n  x: 1.6685314128763346e-05\n  y: 7.605423252010559e-07\n  z: 0.5499997691965299\norientation: \n  x: -1.7241159171749294e-06\n  y: -3.4727418375931076e-05\n  z: 7.70399764780472e-06\n  w: -0.999999999365841, position: \n  x: 2.982939556505049e-05\n  y: -1.1026135089835955e-07\n  z: 0.7399994053384645\norientation: \n  x: -0.7071102365180965\n  y: -3.487087125846861e-05\n  z: 4.595618207130001e-05\n  w: -0.7071033234848876, position: \n  x: 5.361324939952988e-05\n  y: -2.617100734835899e-06\n  z: 0.9499991531355039\norientation: \n  x: -5.7857692233718445e-05\n  y: 3.7694976671240333e-06\n  z: -0.9999999974089023\n  w: -4.266701008226583e-05, position: \n  x: 7.032380289830775e-05\n  y: -0.06070425841409702\n  z: 1.1399983341836095\norientation: \n  x: -7.118787130367233e-05\n  y: -0.7071041851772556\n  z: -0.7071093735170815\n  w: 1.1017128010419203e-05, position: \n  x: 8.483071478015996e-05\n  y: -5.035803146175022e-06\n  z: 1.2209985494984597\norientation: \n  x: 4.998606839501499e-06\n  y: 5.634515291003493e-05\n  z: -6.150433267404365e-05\n  w: 0.9999999965087275]'

-

-

In [ ]:
# Functions to extract useful position data from the messy string above.

# Python3 code to demonstrate working of
# Extract String after Nth occurrence of K character
# Using list comprehension and enumerate()
def get_pose_ori(poses,i):
    # initializing string
    test_x = poses.iloc[i,1]

    # printing original string
    #print("The original string is : " + str(test_str))

    # initializing K
    K = 'x'

    # initializing N
    N = 17

    # list comprehension to get the indices of K character
    indices = [i for i, x in enumerate(test_x) if x == K]

    # extracting string after Nth occurrence of K character
    if len(indices) >= N:
        result_pose = test_x[indices[N-1]+1:]
        result_pose = result_pose[2:]
    #    print("The pose_ori :\n " + str(respose))
    #else:
    #    print("Error: K character not found N times in the string.")

    return result_pose

# Leave out the orientations as the are not going to be utilized
def get_poses(poses_ori):
    # Python3 code to demonstrate working of
    # Prefix extraction before specific character
    # Using rsplit()
    # initializing split character
    spl_char = '\nori'
    # printing original string
    #print("The original string is :"+ str(test_y))
    # Using rsplit()
    # Prefix extraction before specific character
    poses_xyz = poses_ori.rsplit(spl_char, 2)[0]
    return poses_xyz

# Split x from the rest and save it to a variable
def get_x_yz(poses_xyz):
    x = poses_xyz.split('\n  y: ')[0]
    yz = poses_xyz.split('\n  y: ')[1]
    return x, yz

# Split y and z from each other
def get_y_z(yz):
    y = yz.split('\n  z: ')[0]
    z = yz.split('\n  z: ')[1]
    return y, z

# Combine all functions in one function
def parse_xyz(poses,i):
    posori = get_pose_ori(poses,i)
    poses_xyz = get_poses(posori)
    x , yz = get_x_yz(poses_xyz)
    y, z = get_y_z(yz)
    return x, y, z

In [ ]:
df_clean_xyz = [parse_xyz(poses,i) for i in range(len(poses))]

In [ ]:
df_clean_xyz = pd.DataFrame(df_clean_xyz)

In [ ]:
df_xyz_timed = pd.concat([poses.iloc[:,0],df_clean_xyz], axis=1)
df_xyz_timed

,Time,0,1,2
0,1054.683,8.483071478015996e-05,-5.035803146175022e-06,1.2209985494984597
1,1054.683,8.429867892710055e-05,-5.042569954274989e-06,1.2209985673775714
2,1054.683,8.483071477987694e-05,-5.035803146175022e-06,1.2209985494984597
3,1054.683,8.42986789276e-05,-5.042569954274989e-06,1.2209985673775714
4,1054.684,8.483071477945005e-05,-5.035803146175022e-06,1.2209985494984597
...,...,...,...,...
299989,1354.681,-0.154205844950229,-0.4714431640968517,0.8014031161208446
299990,1354.681,-0.15415708849764148,-0.47149578522214886,0.8014517067417991
299991,1354.681,-0.15410853930996982,-0.47154805832063773,0.8015005564640846
299992,1354.681,-0.1540597701561851,-0.4716006537270218,0.8015492339847656
299993,1354.681,-0.15401120846115976,-0.4716529004799701,0.801598171086627

In [ ]:
len(df_clean_xyz)

299994

In [ ]:
len(df_angles)

30001

In [ ]:
# df_clean_xyz = pd.DataFrame(df_clean_xyz)
# dataset = pd.concat([df_clean_xyz,df_angles], axis=1)
# dataset

In [ ]:
# Create a new dataframe only with Time column of angles dataset
df_angles_time = df_angles.iloc[:,0:1]

# Leave out columns of df_angle other than angles
df_angles = df_angles.iloc[:,6:13]

print(df_angles.columns)

# Rename columns
df_angles.rename(columns={'position_0': 'theta0',
                          'position_1': 'theta1',
                          'position_2': 'theta2',
                          'position_3': 'theta3',
                          'position_4': 'theta4',
                          'position_5': 'theta5',
                          'position_6': 'theta6'},
                          inplace=True, errors='raise')
df_angles

Index(['position_0', 'position_1', 'position_2', 'position_3', 'position_4',
       'position_5', 'position_6'],
      dtype='object')

         theta0    theta1    theta2    theta3    theta4    theta5    theta6
0      0.000013  0.000071 -0.000026 -0.000045 -0.000070  0.000004 -0.000038
1      0.000013  0.000071 -0.000026 -0.000045 -0.000070  0.000004 -0.000038
2      0.000013  0.000071 -0.000026 -0.000045 -0.000070  0.000004 -0.000038
3      0.000013  0.000071 -0.000026 -0.000045 -0.000070  0.000004 -0.000038
4      0.000013  0.000071 -0.000026 -0.000045 -0.000070  0.000004 -0.000038
...         ...       ...       ...       ...       ...       ...       ...
29996  2.351751 -0.147447 -1.175521  1.350805 -1.044323 -0.414182 -0.395911
29997  2.348598 -0.148008 -1.172338  1.348688 -1.034323 -0.410765 -0.400477
29998  2.345445 -0.148570 -1.169154  1.346571 -1.024323 -0.407348 -0.405044
29999  2.342291 -0.149132 -1.165970  1.344454 -1.014323 -0.403931 -0.409610
30000  2.339138 -0.149693 -1.162786  1.342337 -1.004323 -0.400514 -0.414176

[30001 rows x 7 columns]

In [ ]:
# Concatenate the times and angles
df_angles_timed = pd.concat([df_angles_time,df_angles], axis=1)
df_angles_timed

,Time,theta0,theta1,theta2,theta3,theta4,theta5,theta6
0,1054.683,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
1,1054.691,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
2,1054.701,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
3,1054.711,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
4,1054.721,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
...,...,...,...,...,...,...,...,...
29996,1354.639,2.351751,-0.147447,-1.175521,1.350805,-1.044323,-0.414182,-0.395911
29997,1354.651,2.348598,-0.148008,-1.172338,1.348688,-1.034323,-0.410765,-0.400477
29998,1354.661,2.345445,-0.148570,-1.169154,1.346571,-1.024323,-0.407348,-0.405044
29999,1354.671,2.342291,-0.149132,-1.165970,1.344454,-1.014323,-0.403931,-0.409610
30000,1354.681,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176

In [ ]:
# Concatanate the 3D positions and joint angles
# only merge the samples whose values in Time columns are matching
# This allow the proper syncronisation of xyz and angle values
result_df = pd.merge(df_xyz_timed, df_angles_timed, on='Time', how='inner')

In [ ]:
result_df

,Time,0,1,2,theta0,theta1,theta2,theta3,theta4,theta5,theta6
0,1054.683,8.483071478015996e-05,-5.035803146175022e-06,1.2209985494984597,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
1,1054.683,8.429867892710055e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
2,1054.683,8.483071477987694e-05,-5.035803146175022e-06,1.2209985494984597,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
3,1054.683,8.42986789276e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
4,1054.691,8.429867892703463e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
...,...,...,...,...,...,...,...,...,...,...,...
30289,1354.681,-0.154205844950229,-0.4714431640968517,0.8014031161208446,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30290,1354.681,-0.15415708849764148,-0.47149578522214886,0.8014517067417991,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30291,1354.681,-0.15410853930996982,-0.47154805832063773,0.8015005564640846,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30292,1354.681,-0.1540597701561851,-0.4716006537270218,0.8015492339847656,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30293,1354.681,-0.15401120846115976,-0.4716529004799701,0.801598171086627,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176

In [ ]:
final_dataset = result_df.rename(columns={0: 'x',
                                          1: 'y',
                                          2: 'z'}, errors='raise')

In [ ]:
# The exponential symbols at the end of coordinates are
# automatically converted to number numbers in the csv file.
final_dataset

,Time,x,y,z,theta0,theta1,theta2,theta3,theta4,theta5,theta6
0,1054.683,8.483071478015996e-05,-5.035803146175022e-06,1.2209985494984597,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
1,1054.683,8.429867892710055e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
2,1054.683,8.483071477987694e-05,-5.035803146175022e-06,1.2209985494984597,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
3,1054.683,8.42986789276e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
4,1054.691,8.429867892703463e-05,-5.042569954274989e-06,1.2209985673775714,0.000013,0.000071,-0.000026,-0.000045,-0.000070,0.000004,-0.000038
...,...,...,...,...,...,...,...,...,...,...,...
30289,1354.681,-0.154205844950229,-0.4714431640968517,0.8014031161208446,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30290,1354.681,-0.15415708849764148,-0.47149578522214886,0.8014517067417991,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30291,1354.681,-0.15410853930996982,-0.47154805832063773,0.8015005564640846,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30292,1354.681,-0.1540597701561851,-0.4716006537270218,0.8015492339847656,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176
30293,1354.681,-0.15401120846115976,-0.4716529004799701,0.801598171086627,2.339138,-0.149693,-1.162786,1.342337,-1.004323,-0.400514,-0.414176

In [ ]:
# Save the final dataset as it is now ready for the training.
final_dataset.to_csv('gazebo_dataset_sync_4.csv', index=False)